# Generated by Django 2.2.6 on 2019-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(verbose_name='Time published'),
        ),
    ]
