# Generated by Django 2.2.6 on 2019-11-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191103_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=400, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(verbose_name='Comment time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.IntegerField(default=0, verbose_name='Replies'),
        ),
        migrations.AlterField(
            model_name='post',
            name='confession',
            field=models.CharField(max_length=4000, verbose_name='Confession'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_text',
            field=models.CharField(max_length=400, verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_time',
            field=models.DateTimeField(verbose_name='Reply time'),
        ),
    ]
