# Generated by Django 2.2.6 on 2019-11-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20191103_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_appreciations',
            field=models.PositiveIntegerField(default=0, verbose_name='Appreciations'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_downvotes',
            field=models.PositiveIntegerField(default=0, verbose_name='Downvotes'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_appreciations',
            field=models.PositiveIntegerField(default=0, verbose_name='Appreciations'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_appreciations',
            field=models.PositiveIntegerField(default=0, verbose_name='Appreciations'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_downvotes',
            field=models.PositiveIntegerField(default=0, verbose_name='Downvotes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
        ),
    ]
