# Generated by Django 2.2.6 on 2019-11-03 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20191103_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_appreciations',
            new_name='appreciations',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_downvotes',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_appreciations',
            new_name='appreciations',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_views',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_appreciations',
            new_name='appreciations',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_downvotes',
            new_name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_time',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_text',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='This is a comment', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='text',
            field=models.CharField(default='This is a reply', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 14, 16, 38, 938809, tzinfo=utc), verbose_name='Timestamp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
        ),
    ]
