# Generated by Django 2.2.6 on 2019-11-04 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20191104_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='time',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='comment',
            name='mod_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mod_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='n_comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='mod_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
        ),
    ]
