# Generated by Django 2.2.6 on 2019-11-04 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('PR', 'private'), ('PB', 'public'), ('CM', 'Communities')], default='PB', max_length=2)),
                ('dream', models.CharField(blank=True, max_length=600)),
                ('ambition', models.CharField(blank=True, max_length=600)),
                ('bio', models.CharField(blank=True, max_length=600)),
                ('status', models.CharField(blank=True, max_length=600)),
                ('philosophy', models.CharField(blank=True, max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
