# Generated by Django 2.2.7 on 2019-11-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191106_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
