# Generated by Django 2.2.7 on 2019-11-09 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('PR', 'private'), ('PB', 'public'), ('CM', 'Communities')], default='PB', max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('dream', models.TextField(blank=True, max_length=400)),
                ('ambition', models.TextField(blank=True, max_length=400)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('philosophy', models.TextField(blank=True, max_length=200)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
